### PR TITLE
Edit command fixed

### LINKED ISSUE #146: EditCommand
image
User should be able to edit the date under such circumstances.

### LINKED ISSUE #153: ListCommandbug
1. First bug:
image

2. Second bug:
When I type the input appeared in the UG: `list d/2020-03-16 t/15:00 c/todo`
image

I would suggest to write the UG for the command you implement, or others may not sure what is your UG.
However, for list/delete command, I have no idea what is the UG is. Please @yuchenlichuck fix the bug and write UG carefully.

### PR DESCRIPTION
**Pull request by JTWang2000**

### CODE REVIEW

File: src/main/java/seedu/tasks/Task.java [hunk 1]
```diff
@@ -20,6 +20,9 @@
     protected ArrayList<LocalDate> date = new ArrayList<LocalDate>();
     protected ArrayList<LocalTime> time = new ArrayList<LocalTime>();
     protected ArrayList<String> location = new ArrayList<String>();
+
+    protected boolean isDateSetByUser = false;//check if need to automatically populate data
```
Comment (yuchenlichuck) [inline src/main/java/seedu/tasks/Task.java:24]: maybe change the comment to next line
